### PR TITLE
Tester to check wether the ssl protocols really work

### PR DESCRIPTION
**Pull request by amohtashami12307**
Option for clients to choose the ssl protocol they want to use.

### CODE REVIEW

**Comment by mythz** [comment]
Cheers 👍

**Comment by devathis** [comment]
Hi,
We are using ServiceStack.Redis V 4.0.50.0 dll to connect the Azure Cache REDIS.
Using the .NET Framework 4.5 and Visual Studio 2013. We want to upgrade the TLS Version 1.0 to TLS V1.2. After changing the version my code is not working . getting the below error System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host.

Added sslprotocols in connection string but it'not worked.
 XXXXXXXXXXXXXXXXX=@dev-mnredis01.redis.cache.windows.net?ssl=true&amp;sslprotocols=Tls12

Tried to add the below one no luck.
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Please help us where I need to add the code to support my code TLS V1.2. March 30 is the last for this.

Regards,
Suresh 
+91 9000480011

**Comment by mythz** [comment]
@devathis Pull Requests are not the place for technical support. If you're a current ServiceStack Customer you can report issues at https://github.com/ServiceStack/Issues if you're not you can [ask questions on StackOverflow](https://stackoverflow.com/questions/ask?tags=servicestack) with the `servicestack` tag.

**Comment by devathis** [comment]
Ok. Thanks

**Pull request merged**
