### PR TITLE
Redis INFO parser was added to RedisDataInfoExtension

### PR DESCRIPTION
**Pull request by IvAlex1986**
Hello ServiceStack Team,

Please review my Pull Request.
I have added parser for INFO comand (http://redis.io/commands/info).
New extension method convert INFO data to JSON format.

Best regards,
Alexander

### CODE REVIEW

**Comment by mythz** [comment]
Hi, you should not be referencing any additional dependencies like this is doing with `System.Web.Extensions` and `JavaScriptSerializer`. It's puzzling why you wouldn't use the existing ServiceStack.Text JsonSerializer for any JSON Serialization as done withing the rest of this library?

Also can you [approve the Contributor License Agreement](https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform) so we can accept any contributions.

**Comment by IvAlex1986** [comment]
Please review new commit (fix JsonSerializer).

I agree your Contributor License Agreement.

**Comment by mythz** [comment]
Hi, I still can't see a record of having [approved the contributor License Agreement](https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform) containing your GitHub IvAlex1986 username?

**Comment by IvAlex1986** [comment]
Please review new commit (fix JsonSerializer).

I agree your Contributor License Agreement.

**Comment by IvAlex1986** [comment]
Check the contributor License Agreement again.
I have submitted the form.

**Comment by mythz** [comment]
Cheers 👍

**Pull request merged**
