### PR TITLE
Sentinel improvements and overloads

### PR DESCRIPTION
**Pull request by andyberryman**

### CODE REVIEW

**Comment by mythz** [comment]
Hi Andy, Can you also [approve the Contributor License Agreement](https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform) so we take a look at this pull request.

Also can you separate the commits for additional API with the breaking changes to the Sentinel API so they can be evaluated separately.

**Comment by andyberryman** [comment]
I made all of my changes such that they were overloads rather than breaking changes.  So I'm not sure which specific ones you would like for me the break out.

**Comment by mythz** [comment]
I'm referring to the additional `Start()` and `Setup()` overload which are quite disruptive, I also had a quick glance to see Obsolete being added and it initially looked like it was being added to existing APIs.

Also the solution to pass additional options to the underlying Pooled Connection managers are listed at:
https://github.com/ServiceStack/Issues/issues/216#issuecomment-69800142

Basically being able to provide a factory to return a configured instance of `PooledRedisClientManager`:

```csharp
var sentinel = new RedisSentinel([]{"127.0.0.1:6379"}, "mymaster") {
    RedisManagerFactory =
    {
        FactoryFn = (writeHosts, readHosts) =>
            new PooledRedisClientManager(writeHosts, readHosts, initalDb:1)
    }
};
```

Also an option to append these options on the Redis Connection string, e.g:

```csharp
var sentinel = new RedisSentinel([]{"127.0.0.1:6379"}, "mymaster") {
    HostFilter = host => host + "?db=1"
};
```

I prefer this approach which is less disruptive, more configurable and requires less surface area.

**Comment by andyberryman** [comment]
Ok ... I missed the exposure of that factory overload.  I can definitely use that to handle my desire to pass in the overloads for the connection pool settings.

**Comment by mythz** [comment]
Hi Andy, yeah if you can remove the sentinel changes I can merge the rest.

**Comment by andyberryman** [comment]
OK ... I think that I removed everything that we discussed.  What's left is the Union and Intersect changes as well as the change to return a Read-Write Client when no Read-Only servers are available.

**Comment by andyberryman** [comment]
Wait ... There's one other change I need to get in there.  The one for detecting a command-line sentinel failover.  Working on merging that now.

**Comment by andyberryman** [comment]
Ok ... Should be good now.

**Comment by mythz** [comment]
Was hoping to see a new PR with only the changes as these reverts pollute the commit history, so I ended up just cherry picking changes from this PR into this commit: https://github.com/ServiceStack/ServiceStack.Redis/commit/589b88192ea798cc87cbd8441f8a7e0099761311

**Comment by mythz** [comment]
FYI these changes is now available on MyGet: https://github.com/ServiceStack/ServiceStack/wiki/MyGet

**Comment by andyberryman** [comment]
Ok ... Thanks ... Now that I know better how you like to see things ... I'll do better next time.

**Pull request closed without merging**
